# Generated by Django 3.2.9 on 2021-12-08 14:32

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('publication_year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), core.models.max_value_current_year])),
                ('language', models.CharField(max_length=100)),
                ('no_of_actual_copies', models.PositiveIntegerField(default=0)),
                ('no_of_copies_current', models.PositiveIntegerField(default=0)),
                ('publisher', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Book Details',
            },
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_from_date', models.DateField(null=True)),
                ('borrowed_to_date', models.DateField(null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('is_return', models.BooleanField(default=False)),
                ('books', models.ManyToManyField(to='core.BookDetails')),
            ],
            options={
                'verbose_name_plural': 'Borrower',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=12, unique=True)),
                ('borrower', models.ManyToManyField(to='core.Borrower')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
    ]
