# Generated by Django 3.2.1 on 2021-12-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_department_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
