# Generated by Django 3.2.1 on 2021-12-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bookdetails_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='borrower',
            field=models.ManyToManyField(blank=True, to='core.Borrower'),
        ),
    ]
