# Generated by Django 3.2.1 on 2021-12-21 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_studentdetails_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='books',
        ),
        migrations.AddField(
            model_name='borrower',
            name='books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bookdetails'),
        ),
    ]
