# Generated by Django 3.2.1 on 2021-12-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211221_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='books',
            new_name='book',
        ),
    ]
